import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("practice hub opens active tracker modes without setup screen", () => {
  const page = readFileSync("app/page.tsx", "utf8");
  const styles = readFileSync("app/globals.css", "utf8");
  const attendanceListBlocks = styles.match(/\.attendance-roster__list \{[^}]+\}/g) ?? [];

  assert.match(page, /type PracticeHubTab = "Overview" \| "Metrics" \| "History"/);
  assert.match(page, /type PracticeDrilldown = \{ kind: "hub" \} \| \{ kind: "attendance" \} \| \{ kind: "review"; practiceId: ID \}/);
  assert.match(page, /function PracticeHome\(/);
  assert.match(page, /function PracticeReview\(/);
  assert.match(page, /function PracticeAttendanceDrilldown\(/);
  assert.doesNotMatch(page, /function PracticeSessionSetup\(/);
  assert.doesNotMatch(page, /function PracticeDrillsTab/);
  assert.doesNotMatch(page, /function PracticeThrowingTab/);
  assert.doesNotMatch(page, /kind: "setup"/);
  assert.match(page, /function PracticeConsole\(/);
  assert.match(page, /function availablePracticePlayers\(/);
  assert.match(page, /return status === "Present" \|\| status === "Late"/);
  assert.match(page, /const HITTING_STATIONS: HittingSession\["type"\]\[\] = \["Tee", "Front Toss", "Machine", "Coach BP", "Other"\]/);
  assert.match(page, /const LIVE_BP_THROWER_SOURCES: LiveBpThrowerSource\[\] = \["PLAYER", "COACH", "MACHINE"\]/);
  assert.match(page, /\(\["Overview", "Metrics", "History"\] as PracticeHubTab\[\]\)/);
  assert.doesNotMatch(page, /\(\["Overview", "Drills", "Throwing", "Metrics", "History"\]/);
  assert.match(page, /const HITTING_RESULT_ACTIONS/);
  assert.match(page, /label: "Hard LD"/);
  assert.match(page, /const HITTING_CONTACT_CHOICES/);
  assert.match(page, /exitVelocityMph/);
  assert.match(page, /function clearPendingHittingContext\(\)/);
  assert.match(page, /onTrackExitVelocity/);
  assert.match(page, /practice-hitting-shell/);
  assert.match(page, /practice-hitting-rail/);
  assert.match(page, /practice-hitting-log-trigger/);
  assert.match(page, /Log Swing/);
  assert.match(page, /What happened\?/);
  assert.match(page, /Skip Location/);
  assert.match(page, /practice-live-bp-pitch-button/);
  assert.match(page, /practice-live-bp-pitch-sheet/);
  assert.match(page, /Pitch result/);
  assert.match(page, /function PracticeSprayField/);
  assert.match(page, /function deriveHitDirectionFromFieldLocation/);
  assert.match(page, /practicePitchTypeLabel/);
  assert.match(page, /attendance-roster__scroll/);
  assert.match(page, /practice-player-strip__player-scroll/);
  assert.match(page, /practice-tracker-tabs/);
  assert.match(page, /PracticeRecentEventTable/);
  assert.match(page, /Undo Last/);
  assert.match(page, /function openPracticeStation\(mode: PracticeMode, options: \{ hittingStation\?: HittingSession\["type"\] \} = \{\}\)/);
  assert.match(page, /function openCurrentPractice\(currentPractice = practice\)/);
  assert.match(page, /function openOrStartPractice\(\)/);
  assert.match(page, /hasOpenPractice=\{Boolean\(practice && !practice\.endedAt\)\}/);
  assert.match(page, /onStartPractice=\{openOrStartPractice\}/);
  assert.match(page, /if \(options\.openPractice && practice && !practice\.endedAt\)/);
  assert.match(page, /const existingOpenPractice = activePractice\(current\)/);
  assert.match(page, /if \(options\.openPractice && existingOpenPractice && !existingOpenPractice\.endedAt\) return current/);
  assert.match(page, /const currentOpenPractice = activePracticeRecord && !activePracticeRecord\.endedAt \? activePracticeRecord : undefined/);
  assert.match(page, /title=\{currentOpenPractice \? "Current Practice"/);
  assert.match(page, /cta=\{currentOpenPractice \|\| nextPractice \? "Open" : "Start"\}/);
  assert.match(page, /function openHittingQuickStart\(station: HittingSession\["type"\]\)/);
  assert.match(page, /openPracticeStation\("Hitting", \{ hittingStation: station \}\)/);
  assert.match(page, /function changeLiveBpThrowerSource\(source: LiveBpThrowerSource\)/);
  assert.match(page, /onLiveBpThrowerSource=\{changeLiveBpThrowerSource\}/);
  assert.match(page, /liveBpThrowerSource=\{liveBpThrowerSource\}/);
  assert.match(page, /liveBpThrowerSourceLabel/);
  assert.match(page, /liveBpThrowerSource !== "PLAYER"/);
  assert.match(page, /onStartHittingStation=\{openHittingQuickStart\}/);
  assert.match(page, /setPracticeTrackingOpen\(true\)/);
  assert.match(page, /onOpenAttendance=\{\(\) => \(practice \? setPracticeDrilldown\(\{ kind: "attendance" \}\)/);
  assert.match(page, /onOpenPracticeReview=\{\(practiceId\) => setPracticeDrilldown\(\{ kind: "review", practiceId \}\)\}/);
  assert.match(page, /onOpenStation=\{openPracticeStation\}/);
  assert.match(page, /onUndo=\{undoPracticeEvent\}/);
  assert.match(page, /function openPracticeAnalytics\(practiceId: ID, category: PracticeMetricsCategory = "Hitting", playerId\?: ID\)/);

  assert.doesNotMatch(page, /Hard Contact<\/button>/);
  assert.doesNotMatch(page, /PITCH<\/button>/);
  assert.doesNotMatch(page, />Drills<\/button>/);
  assert.doesNotMatch(page, />Throwing<\/button>/);
  assert.doesNotMatch(page, /PracticeDashboardStrip/);
  assert.doesNotMatch(page, /PracticeLeadersCard/);
  assert.match(page, /StrikeZone points=\{pitchEvents\.map/);
  assert.match(page, /function PracticeMetricsTab/);
  assert.match(page, /function PracticeHistoryTab/);
  assert.match(page, /buildPracticeMetricRows\(data, category, practiceId\)/);
  assert.match(page, /practiceMetricSummary\(data, category, practiceId\)/);
  assert.match(page, /function buildPracticeReviewSessions/);
  assert.match(page, /View Full Practice Analytics/);
  assert.match(page, /role="columnheader"/);
  assert.match(page, /View History/);

  assert.match(styles, /\.practice-summary-strip/);
  assert.match(styles, /\.practice-hitting-start-popover/);
  assert.match(styles, /\.practice-metrics-page/);
  assert.match(styles, /\.attendance-roster__scroll \.scroll-cue-panel__body \{[\s\S]*max-height: min\(44dvh, 440px\)/);
  assert.match(styles, /\.attendance-roster__scroll \.scroll-cue-panel__body \{[\s\S]*padding-bottom: 30px/);
  assert.ok(attendanceListBlocks.some((block) => block.includes("overflow-y: auto")));
  assert.ok(attendanceListBlocks.every((block) => !block.includes("overflow: visible")));
  assert.match(styles, /\.practice-activity-card--pitching/);
  assert.match(styles, /\.practice-tracker-tabs/);
  assert.match(styles, /\.practice-player-strip/);
  assert.match(styles, /\.live-bp-context-bar/);
  assert.match(styles, /\.live-bp-source-segments/);
  assert.match(styles, /\.live-bp-thrower-card/);
  assert.match(styles, /\.practice-hitting-shell/);
  assert.match(styles, /\.practice-hitting-sheet/);
  assert.match(styles, /\.practice-hitting-rail/);
  assert.match(styles, /\.practice-live-bp-action-panel/);
  assert.match(styles, /\.practice-live-bp-pitch-sheet/);
  assert.match(styles, /\.practice-review-summary-strip/);
  assert.match(styles, /\.practice-review-table/);
  assert.match(styles, /\.practice-spray-field/);
});
