import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("practice hub opens active tracker modes without setup screen", () => {
  const page = readFileSync("app/page.tsx", "utf8");
  const layout = readFileSync("app/layout.tsx", "utf8");
  const styles = readFileSync("app/globals.css", "utf8");
  const taxonomy = readFileSync("app/lib/hittingTaxonomy.ts", "utf8");
  const analytics = readFileSync("app/lib/analyticsQuery.ts", "utf8");
  const analyticsCatalog = readFileSync("app/lib/analyticsCatalog.ts", "utf8");
  const sharedField = readFileSync("app/components/ClubhouseBaseballField.tsx", "utf8");
  const types = readFileSync("app/types.ts", "utf8");
  const attendanceListBlocks = styles.match(/\.attendance-roster__list \{[^}]+\}/g) ?? [];

  assert.match(page, /type PracticeHubTab = "Overview" \| "Metrics" \| "History"/);
  assert.match(page, /type PracticeDrilldown = \{ kind: "hub" \} \| \{ kind: "attendance" \} \| \{ kind: "review"; practiceId: ID \}/);
  assert.match(page, /function PracticeHome\(/);
  assert.match(page, /function PracticeReview\(/);
  assert.match(page, /function PracticeAttendanceDrilldown\(/);
  assert.doesNotMatch(page, /function PracticeSessionSetup\(/);
  assert.doesNotMatch(page, /function PracticeDrillsTab/);
  assert.doesNotMatch(page, /function PracticeThrowingTab/);
  assert.doesNotMatch(page, /kind: "setup"/);
  assert.match(page, /function PracticeConsole\(/);
  assert.match(page, /function availablePracticePlayers\(/);
  assert.match(page, /function stablePracticeLineupPlayers\(/);
  assert.match(page, /return status === "Present" \|\| status === "Late"/);
  assert.match(page, /const HITTING_STATIONS: HittingSession\["type"\]\[\] = \["Tee", "Front Toss", "Machine", "Coach BP", "Other"\]/);
  assert.match(page, /const LIVE_BP_THROWER_SOURCES: LiveBpThrowerSource\[\] = \["PLAYER", "COACH", "MACHINE"\]/);
  assert.match(page, /\(\["Overview", "Metrics", "History"\] as PracticeHubTab\[\]\)/);
  assert.doesNotMatch(page, /\(\["Overview", "Drills", "Throwing", "Metrics", "History"\]/);
  assert.match(page, /const HITTING_RESULT_ACTIONS/);
  assert.match(taxonomy, /PRACTICE_HITTING_RESULT_OPTIONS/);
  assert.match(taxonomy, /label: "Hard Ground Ball"/);
  assert.match(taxonomy, /label: "Hard Fly Ball"/);
  assert.match(taxonomy, /label: "Line Drive"/);
  assert.match(taxonomy, /isPracticeHardContactEvent/);
  assert.match(taxonomy, /defaultPracticeHittingPitchMode/);
  assert.match(taxonomy, /HittingPitchTrackingMode/);
  assert.doesNotMatch(page, /function createHittingContactDraft/);
  assert.match(page, /const HITTING_CONTACT_CHOICES/);
  assert.match(page, /exitVelocityMph/);
  assert.match(page, /hittingPitchTrackingMode/);
  assert.match(page, /onHittingPitchTrackingMode/);
  assert.match(page, /practice-hitting-quick-controls/);
  assert.match(page, /practice-hitting-pitch-panel/);
  assert.match(page, /practice-hitting-stats-scope/);
  assert.match(page, /practice-hitting-session-filter/);
  assert.match(page, /trackHittingPitchLocation/);
  assert.match(page, /pitchLocation: trackHittingPitchLocation \? pitchLocationPoint : undefined/);
  assert.match(page, /PracticeHittingChartCarousel/);
  assert.match(page, /PracticeHittingPitchLocationGrid/);
  assert.match(page, /nextHittingChartMetricMode/);
  assert.match(page, /label: "Hard Contact"/);
  assert.match(page, /label: "Max EV"/);
  assert.match(page, /function updateHittingEvent/);
  assert.match(page, /onUpdateHittingEvent=\{updateHittingEvent\}/);
  assert.match(page, /function clearPendingHittingContext\(\)/);
  assert.match(page, /onTrackExitVelocity/);
  assert.match(page, /practice-hitting-shell/);
  assert.match(page, /practice-hitting-rail/);
  assert.match(page, /practice-hitting-log-trigger/);
  assert.match(page, /practice-hitting-more-trigger/);
  assert.match(page, /Tracking Settings/);
  assert.match(page, /Track Exit Velocity/);
  assert.match(page, /Track Spray Location/);
  assert.match(page, /editingHittingEventId/);
  assert.match(page, /function MobileMoreMenu/);
  assert.match(page, /function MobilePinnedMenu/);
  assert.match(page, /function useBottomNavMenuStyle/);
  assert.match(layout, /export const viewport/);
  assert.match(layout, /width: "device-width"/);
  assert.match(layout, /viewportFit: "cover"/);
  assert.match(page, /const showMobilePinned = !inTeamContext && pinnedTeams\.length > 0/);
  assert.match(page, /\{ key: "teamHome", label: "Team Home", shortLabel: "Home"/);
  assert.match(page, /aria-label=\{label\}/);
  assert.match(page, /aria-current=\{view === key \? "page" : undefined\}/);
  assert.match(page, /team-workspace-header--compact/);
  assert.match(page, /Clubhouse Home/);
  assert.match(page, /"mobile-more-menu__row"/);
  assert.match(page, /"--bottom-nav-count": mobileNavCount/);
  assert.match(page, /className="mobile-more-menu__avatar"/);
  assert.match(page, /<span>Pinned<\/span>/);
  assert.match(page, /aria-label="Pinned teams"/);
  assert.match(page, /onTheme=\{setThemePreference\}/);
  assert.match(page, /<h2>Appearance<\/h2>/);
  assert.match(page, /Log Swing/);
  assert.doesNotMatch(page, /What happened\?/);
  assert.doesNotMatch(page, /Foul and Miss save immediately/);
  assert.doesNotMatch(page, /Active now/);
  assert.match(page, /Knuckleball/);
  assert.match(page, /aria-label="Hitting session type"/);
  assert.match(page, /practice-hitting-sheet__toggle/);
  assert.doesNotMatch(page, /Save Swing<\/button>[\s\S]{0,240}Skip Location/);
  assert.match(page, /practice-live-bp-pitch-button/);
  assert.match(page, /practice-live-bp-pitch-sheet/);
  assert.match(page, /Pitch result/);
  assert.match(page, /practice-pitching-shell/);
  assert.match(page, /practice-pitching-session-select practice-session-select/);
  assert.match(page, /practice-pitching-entry-bar/);
  assert.match(page, /function PracticePitchLocationGrid/);
  assert.match(page, /type PitchLocationMetricMode = PracticeChartMetricMode/);
  assert.match(page, /metricMode: nextPitchLocationMetricMode\(currentMetricMode\)/);
  assert.match(page, /function pitchLocationHeatOpacity/);
  assert.match(page, /function pitchLocationHeatColor/);
  assert.match(page, /function pitchLocationBucketMetricLabel/);
  assert.match(page, /practice-pitch-location-grid__bucket-metric/);
  assert.match(page, /PITCH_LOCATION_BUCKETS/);
  const pitchBucketBlock = page.match(/const PITCH_LOCATION_BUCKETS[\s\S]*?\];/)?.[0] ?? "";
  assert.equal((pitchBucketBlock.match(/id: "pitch_r/g) ?? []).length, 25);
  assert.equal((pitchBucketBlock.match(/isZone: true/g) ?? []).length, 9);
  assert.equal((pitchBucketBlock.match(/isZone: false/g) ?? []).length, 16);
  assert.equal((pitchBucketBlock.match(/isCorner: true/g) ?? []).length, 4);
  assert.doesNotMatch(page, /bucket\.shortLabel/);
  assert.match(page, /LEGACY_PITCH_LOCATION_ID_MAP/);
  assert.match(page, /practice-pitch-location-grid__marker-layer/);
  assert.match(page, /pitchLocationOrientationLabels/);
  assert.doesNotMatch(page, /Catcher View/);
  assert.match(page, /type HittingSheetStep = "setup" \| "result" \| "detail"/);
  assert.match(page, /practice-hitting-sheet__flow/);
  assert.match(page, /aria-label="Switch hitting charts"/);
  assert.match(page, /function selectChartView/);
  assert.match(page, /onChange\(String\(option\)\);\s*setOpen\(false\);/);
  assert.match(page, /Pitch Filter/);
  assert.match(page, /pitchingLivePitchFilters/);
  assert.match(page, /All Players/);
  assert.match(page, /Track Pitch Type/);
  assert.match(page, /Track Velocity/);
  assert.match(page, /Track Location/);
  assert.match(page, /Log Pitch/);
  assert.match(page, /pitchingPitchTrackingMode === "MULTI"/);
  assert.match(page, /pitchingPitchTrackingMode === "ONE"/);
  assert.match(page, /const pitchingSaveDisabled = trackPitchLocation && !pitchingDraft\.location/);
  assert.match(page, /disabled=\{pitchingSaveDisabled\}/);
  assert.match(page, /outcome: isPitchLocationInZone\(point\) \? "Called Strike" : "Ball"/);
  assert.match(page, /onUpdatePitchEvent=\{updatePitchEvent\}/);
  assert.match(page, /formatPitchingEventDetail/);
  assert.match(types, /export type PitchLocationZoneId =/);
  assert.match(types, /export type PitchLocationGridZoneId =/);
  assert.match(types, /pitch_r3c3/);
  assert.match(types, /zone_middle_middle/);
  assert.match(types, /outside_down_glove/);
  assert.match(analyticsCatalog, /metric\("zonePct", "Zone%"/);
  assert.match(analytics, /isAnalyticsZonePoint/);
  assert.match(page, /function PracticeSprayField/);
  assert.match(page, /<ClubhouseBaseballField/);
  assert.match(sharedField, /getSprayDistribution/);
  assert.match(sharedField, /baseball-field-spray-chart-v1\.png/);
  assert.match(sharedField, /canonicalPointToLegacyGame/);
  assert.match(sharedField, /clubhouse-baseball-field__sector-label/);
  assert.match(page, /function deriveHitDirectionFromFieldLocation/);
  assert.match(page, /practicePitchTypeLabel/);
  assert.match(page, /attendance-roster__scroll/);
  assert.match(page, /practice-player-strip__player-scroll/);
  assert.match(page, /practice-tracker-tabs/);
  assert.match(page, /PracticeRecentEventTable/);
  assert.match(page, /Undo Last/);
  assert.match(page, /function openPracticeStation\(mode: PracticeMode, options: \{ hittingStation\?: HittingSession\["type"\] \} = \{\}\)/);
  assert.match(page, /function openCurrentPractice\(currentPractice = practice\)/);
  assert.match(page, /function openOrStartPractice\(\)/);
  assert.match(page, /hasOpenPractice=\{Boolean\(practice && !practice\.endedAt\)\}/);
  assert.match(page, /onStartPractice=\{openOrStartPractice\}/);
  assert.match(page, /if \(options\.openPractice && practice && !practice\.endedAt\)/);
  assert.match(page, /const existingOpenPractice = activePractice\(current\)/);
  assert.match(page, /if \(options\.openPractice && existingOpenPractice && !existingOpenPractice\.endedAt\) return current/);
  assert.match(page, /const currentOpenPractice = activePracticeRecord && !activePracticeRecord\.endedAt \? activePracticeRecord : undefined/);
  assert.match(page, /title=\{currentOpenPractice \? "Current Practice"/);
  assert.match(page, /cta=\{currentOpenPractice \|\| nextPractice \? "Open" : "Start"\}/);
  assert.match(page, /function openHittingQuickStart\(station: HittingSession\["type"\]\)/);
  assert.match(page, /openPracticeStation\("Hitting", \{ hittingStation: station \}\)/);
  assert.match(page, /const PRACTICE_ROUTE_PARAM_KEYS/);
  assert.match(page, /function applyRouteStateFromParams/);
  assert.match(page, /function writePracticeTrackingRoute/);
  assert.match(page, /function writePracticeReviewRoute/);
  assert.match(page, /function writePracticeAttendanceRoute/);
  assert.match(page, /practicePanel", "tracking"/);
  assert.match(page, /practicePanel", "review"/);
  assert.match(page, /function changeLiveBpThrowerSource\(source: LiveBpThrowerSource\)/);
  assert.match(page, /onLiveBpThrowerSource=\{changeLiveBpThrowerSource\}/);
  assert.match(page, /liveBpThrowerSource=\{liveBpThrowerSource\}/);
  assert.match(page, /liveBpThrowerSourceLabel/);
  assert.match(page, /liveBpThrowerSource !== "PLAYER"/);
  assert.match(page, /onStartHittingStation=\{openHittingQuickStart\}/);
  assert.match(page, /setPracticeTrackingOpen\(true\)/);
  assert.match(page, /onOpenAttendance=\{\(\) => \(practice \? writePracticeAttendanceRoute\(\)/);
  assert.match(page, /onOpenPracticeReview=\{\(practiceId\) => writePracticeReviewRoute\(practiceId\)\}/);
  assert.match(page, /onOpenStation=\{openPracticeStation\}/);
  assert.match(page, /onUndo=\{undoPracticeEvent\}/);
  assert.match(page, /function openPracticeAnalytics\(practiceId: ID, category: PracticeMetricsCategory = "Hitting", playerId\?: ID, eventId\?: ID\)/);
  assert.match(page, /detailPlayer/);
  assert.match(page, /function openAnalyticsPlayerDetail/);
  assert.match(page, /window\.history\[options\.replace \? "replaceState" : "pushState"\]/);

  assert.doesNotMatch(page, /Hard Contact<\/button>/);
  assert.doesNotMatch(page, /practice-hitting-quality-toggle/);
  assert.doesNotMatch(page, /practice-hitting-contact-grid/);
  assert.doesNotMatch(page, /practice-hitting-toggles/);
  assert.doesNotMatch(page, /ModalFrame title="More"/);
  assert.doesNotMatch(page, /toggleTheme\(\); setMobileMoreOpen\(false\)/);
  assert.doesNotMatch(page, /PITCH<\/button>/);
  assert.doesNotMatch(page, />Drills<\/button>/);
  assert.doesNotMatch(page, />Throwing<\/button>/);
  assert.doesNotMatch(page, /PracticeDashboardStrip/);
  assert.doesNotMatch(page, /PracticeLeadersCard/);
  assert.doesNotMatch(page, /quick-pad quick-pad--pitching/);
  assert.doesNotMatch(page, /<StatTile label="CSW %"/);
  assert.match(page, /PracticePitchLocationGrid pitches=\{filteredPitchEvents\}/);
  assert.match(page, /PracticePitchLocationGrid[\s\S]{0,120}pitches=\{pitchEvents\}/);
  assert.match(page, /function PracticeMetricsTab/);
  assert.match(page, /function PracticeHistoryTab/);
  assert.match(page, /buildPracticeMetricRows\(data, category, practiceId, effectiveHittingSessionFilterId, effectivePitchingSessionFilterId\)/);
  assert.match(page, /practiceMetricSummary\(data, category, practiceId, effectiveHittingSessionFilterId, effectivePitchingSessionFilterId\)/);
  assert.match(page, /function buildPracticeReviewSessions/);
  assert.match(page, /View Full Practice Analytics/);
  assert.match(page, /role="columnheader"/);
  assert.match(page, /View History/);

  assert.match(styles, /\.practice-summary-strip/);
  assert.match(styles, /\.practice-hitting-start-popover/);
  assert.match(styles, /\.practice-metrics-page/);
  assert.match(styles, /\.attendance-roster__scroll \.scroll-cue-panel__body \{[\s\S]*max-height: min\(44dvh, 440px\)/);
  assert.match(styles, /\.attendance-roster__scroll \.scroll-cue-panel__body \{[\s\S]*padding-bottom: 30px/);
  assert.ok(attendanceListBlocks.some((block) => block.includes("overflow-y: auto")));
  assert.ok(attendanceListBlocks.every((block) => !block.includes("overflow: visible")));
  assert.match(styles, /\.practice-activity-card--pitching/);
  assert.match(styles, /\.practice-tracker-tabs/);
  assert.match(styles, /\.practice-player-strip/);
  assert.match(styles, /\.live-bp-context-bar/);
  assert.match(styles, /\.live-bp-source-segments/);
  assert.match(styles, /\.live-bp-thrower-card/);
  assert.match(styles, /\.practice-hitting-shell/);
  assert.match(styles, /\.practice-pitching-shell/);
  assert.match(styles, /\.practice-pitch-location-grid/);
  assert.match(styles, /\.practice-pitch-location-grid__bucket-metric/);
  assert.match(styles, /@media \(max-width: 640px\) \{[\s\S]*\.practice-console--active \.practice-tracker-tabs \{[\s\S]*position: fixed/);
  assert.match(styles, /@media \(max-width: 640px\) \{[\s\S]*\.practice-console--active \.practice-tracker-tabs \{[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(styles, /@media \(max-width: 640px\) \{[\s\S]*\.practice-console--active \.practice-hitting-metric-line \{[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(styles, /\.practice-hitting-sheet/);
  assert.match(styles, /\.practice-hitting-sheet__context-controls/);
  assert.match(styles, /\.practice-hitting-station-select/);
  assert.match(styles, /\.practice-hitting-sheet__toggle/);
  assert.match(styles, /\.modal-panel\.practice-hitting-sheet \.modal-body,[\s\S]*grid-auto-rows: max-content/);
  assert.match(styles, /@media \(max-width: 560px\) \{[\s\S]*\.practice-summary-actions \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(styles, /@media \(max-width: 560px\) \{[\s\S]*\.modal-panel\.practice-hitting-sheet > \.modal-footer-slot > \.modal-actions,[\s\S]*display: flex/);
  assert.match(styles, /@media \(max-width: 560px\) \{[\s\S]*\.modal-panel\.practice-hitting-sheet \.modal-actions \.primary-button,[\s\S]*width: auto/);
  assert.match(styles, /@media \(max-width: 560px\) \{[\s\S]*\.practice-hitting-sheet__spray-actions button,[\s\S]*flex: 0 1 auto/);
  assert.match(styles, /\.practice-hitting-rail/);
  assert.match(styles, /\.practice-hitting-quick-controls/);
  assert.match(styles, /\.practice-hitting-pitch-panel/);
  assert.match(styles, /\.practice-hitting-session-filter/);
  assert.doesNotMatch(styles, /\.practice-hitting-quality-toggle/);
  assert.match(styles, /\.practice-hitting-more-list/);
  assert.match(styles, /\.practice-hitting-settings-list/);
  assert.match(styles, /\.mobile-more-menu/);
  assert.match(styles, /\.mobile-more-menu \{[\s\S]*max-height: min\(420px, calc\(100dvh - 112px - env\(safe-area-inset-bottom\)\)\)/);
  assert.match(styles, /\.mobile-more-menu \{[\s\S]*overflow-y: auto/);
  assert.match(styles, /\.mobile-more-menu__row/);
  assert.match(styles, /\.mobile-pinned-menu/);
  assert.match(styles, /@media \(max-width: 720px\) \{[\s\S]*\.bottom-nav \{[\s\S]*width: auto;[\s\S]*transform: none/);
  assert.match(styles, /@media \(max-width: 720px\) \{[\s\S]*\.segmented-control,[\s\S]*\.practice-filter-tabs,[\s\S]*\.roster-status-tabs \{[\s\S]*overflow-x: auto/);
  assert.match(styles, /@media \(max-width: 560px\) \{[\s\S]*\.practice-tracker-tabs \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(styles, /@media \(max-width: 680px\) \{[\s\S]*\.practice-hitting-entry-bar \{[\s\S]*grid-template-columns: 1fr/);
  assert.match(styles, /@media \(max-width: 680px\) \{[\s\S]*\.practice-hitting-quick-controls,[\s\S]*\.practice-hitting-inline-pitch,[\s\S]*\.practice-hitting-pitch-modes,[\s\S]*\.practice-hitting-session-filter \{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(86px, 1fr\)\)/);
  assert.match(styles, /@media \(max-width: 980px\) \{[\s\S]*\.ops-main--practice-tracking > \.team-workspace-header--compact \{[\s\S]*display: none/);
  assert.match(styles, /\.team-workspace-header--compact \{[\s\S]*display: none/);
  assert.match(styles, /@media \(max-width: 1180px\) \{[\s\S]*\.team-workspace-header--compact \{[\s\S]*display: grid/);
  assert.match(styles, /--bottom-nav-count/);
  assert.match(styles, /\.bottom-nav button\.active::before/);
  assert.match(styles, /\.account-appearance-setting/);
  assert.match(styles, /\.practice-live-bp-action-panel/);
  assert.match(styles, /\.practice-live-bp-pitch-sheet/);
  assert.match(styles, /\.practice-review-summary-strip/);
  assert.match(styles, /\.practice-review-table/);
  assert.match(styles, /\.practice-spray-field/);
  assert.match(styles, /\.practice-hitting-live-charts/);
  assert.match(styles, /\.practice-hitting-live-charts__tools/);
  assert.match(styles, /\.practice-hitting-live-charts__scroller \{[\s\S]*scroll-snap-type: x mandatory/);
  assert.match(styles, /\.practice-pitch-location-grid--heat \.practice-pitch-location-grid__marker-layer i \{[\s\S]*display: none/);
});
