import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("next build contains the Clubhouse 9 app shell", async () => {
  assert.equal(existsSync(".next"), true);
  assert.equal(existsSync(".next/server"), true);

  const layout = readFileSync("app/layout.tsx", "utf8");
  const page = readFileSync("app/page.tsx", "utf8");
  const branding = readFileSync("app/lib/branding.ts", "utf8");
  const repository = readFileSync("app/data/supabaseRepository.ts", "utf8");
  const profileRoute = readFileSync("app/api/profile/route.ts", "utf8");
  const authAvatarScrubMigration = readFileSync("supabase/migrations/20260811220000_scrub_auth_avatar_metadata.sql", "utf8");
  const workflow = readFileSync(".github/workflows/supabase-migrations.yml", "utf8");
  const bootstrapRoute = readFileSync("app/api/setup/bootstrap/route.ts", "utf8");
  const publicTeamPage = readFileSync("app/team/[id]/page.tsx", "utf8");
  const publicGamePage = readFileSync("app/game/[id]/page.tsx", "utf8");
  const showcaseSeed = readFileSync("supabase/migrations/20260812143000_seed_carolina_showcase_public_team_demo.sql", "utf8");
  const publicGameSeed = readFileSync("supabase/migrations/20260812170000_public_game_detail_pages.sql", "utf8");

  assert.match(layout, /APP_NAME/);
  assert.match(branding, /APP_NAME\s*=\s*"Clubhouse 9"/);
  assert.match(page, /BRAND_ASSETS/);
  assert.match(page, /supabaseAppRepository/);
  assert.doesNotMatch(page, /localPracticeRepository\.load/);
  assert.match(page, /Create Account/);
  assert.match(page, /TeamSwitcher/);
  assert.match(page, /Your account is ready/);
  assert.doesNotMatch(repository, /claim_initial_metrolina_admin/);
  assert.match(profileRoute, /avatar_url:\s*null/);
  assert.match(profileRoute, /Keep images out of auth metadata/);
  assert.match(authAvatarScrubMigration, /update auth\.users/);
  assert.match(authAvatarScrubMigration, /raw_user_meta_data[\s\S]*-\s*'avatar_url'/);
  assert.match(workflow, /supabase\/setup-cli@v2/);
  assert.match(workflow, /SUPABASE_ACCESS_TOKEN/);
  assert.match(workflow, /SUPABASE_DB_PASSWORD/);
  assert.match(workflow, /SUPABASE_PROJECT_ID/);
  assert.match(bootstrapRoute, /authorizeSetupUser/);
  assert.match(bootstrapRoute, /bootstrap_metrolina_admin/);
  assert.match(publicTeamPage, /type PublicTeamTab = "games" \| "roster" \| "stats" \| "info"/);
  assert.match(publicTeamPage, /<GamesTab team=\{team\} gameMode=\{gameMode\} record=\{record\} \/>/);
  assert.match(publicTeamPage, /normalizeTab\(query\.tab\)/);
  assert.match(publicTeamPage, /PublicTeamHeader/);
  assert.match(publicTeamPage, /href=\{`\/game\/\$\{game\.id\}`\}/);
  assert.match(publicGamePage, /type GameTab = "preview" \| "summary" \| "play-by-play" \| "box-score" \| "info"/);
  assert.match(publicGamePage, /normalizeTab\(query\.tab, final\)/);
  assert.match(publicGamePage, /final \? "summary" : "preview"/);
  assert.match(publicGamePage, /Score by Innings/);
  assert.match(publicGamePage, /Play-by-play will appear once the game begins/);
  assert.match(publicGameSeed, /create table if not exists public\.public_game_details/);
  assert.match(publicGameSeed, /14a90000-0000-4000-8000-000000000004/);
  assert.match(publicGameSeed, /PP 80/);
  assert.match(publicGameSeed, /play_by_play/);
  assert.match(showcaseSeed, /'final', 6, 3, 'W'/);
  assert.match(showcaseSeed, /Pineville Post 80/);
  assert.doesNotMatch(showcaseSeed, /'completed',/);
});
