import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("staff invitation migration keeps tokens hashed and authorization server-side", () => {
  const migration = readFileSync("supabase/migrations/20260811000000_staff_invitations.sql", "utf8");
  const acceptanceFixMigration = readFileSync("supabase/migrations/20260811141000_fix_staff_invitation_acceptance.sql", "utf8");
  const conflictTargetFixMigration = readFileSync("supabase/migrations/20260811145000_fix_staff_invitation_acceptance_conflict_target.sql", "utf8");
  const organizationManagementMigration = readFileSync("supabase/migrations/20260812113000_organization_management.sql", "utf8");
  const invitationCompatibilityMigration = readFileSync("supabase/migrations/20260812115000_restore_staff_invitation_compatibility.sql", "utf8");
  const remoteVerifyWorkflow = readFileSync(".github/workflows/supabase-remote-verify.yml", "utf8");
  const remoteVerifySql = readFileSync("scripts/verify-remote-supabase.sql", "utf8");
  const remoteAcceptanceRegression = readFileSync("scripts/verify-staff-invitation-acceptance.sql", "utf8");
  const createRoute = readFileSync("app/api/staff/invitations/route.ts", "utf8");
  const invitations = readFileSync("app/lib/invitations.ts", "utf8");
  const siteUrl = readFileSync("app/lib/siteUrl.ts", "utf8");
  const acceptRoute = readFileSync("app/api/staff/invitations/accept/route.ts", "utf8");
  const lookupRoute = readFileSync("app/api/staff/invitations/lookup/route.ts", "utf8");
  const memberRoute = readFileSync("app/api/staff/members/[staffMemberId]/route.ts", "utf8");

  assert.match(migration, /create table if not exists public\.staff_members/);
  assert.match(migration, /create table if not exists public\.staff_team_memberships/);
  assert.match(migration, /create table if not exists public\.team_invitations/);
  assert.match(migration, /token_hash text not null unique/);
  assert.doesNotMatch(migration, /\braw_token\b|\bplain_token\b|\binvite_token text\b/i);
  assert.match(migration, /security definer[\s\S]*create_staff_invitation/);
  assert.match(migration, /security definer[\s\S]*accept_staff_invitation/);
  assert.match(migration, /alter table public\.staff_members enable row level security/);
  assert.match(migration, /alter table public\.team_invitations enable row level security/);
  assert.match(migration, /current_profile_can_admin_team/);

  assert.match(acceptanceFixMigration, /create or replace function public\.accept_staff_invitation\(invite_token_hash text\)/);
  assert.match(acceptanceFixMigration, /security definer/);
  assert.match(acceptanceFixMigration, /from public\.team_invitation_memberships as tim\s+where tim\.invitation_id = v_invitation\.id/);
  assert.match(acceptanceFixMigration, /return query\s+select\s+v_invitation\.id::uuid,\s+v_linked_staff_member_id::uuid,\s+v_memberships_created::integer/s);
  assert.doesNotMatch(acceptanceFixMigration, /from public\.team_invitation_memberships\s+where invitation_id =/);
  assert.match(conflictTargetFixMigration, /update public\.staff_team_memberships as stm/);
  assert.match(conflictTargetFixMigration, /where stm\.staff_member_id = v_linked_staff_member_id/);
  assert.doesNotMatch(conflictTargetFixMigration, /on conflict\s*\(\s*staff_member_id/i);
  assert.doesNotMatch(conflictTargetFixMigration, /from public\.team_invitation_memberships\s+where invitation_id =/);
  assert.match(remoteVerifyWorkflow, /verify-staff-invitation-acceptance\.sql/);
  assert.match(remoteAcceptanceRegression, /public\.accept_staff_invitation\(v_fixture\.token_hash\)/);
  assert.match(remoteAcceptanceRegression, /ti\.status[\s\S]*ACCEPTED/);
  assert.match(remoteAcceptanceRegression, /profile_team_memberships/);
  assert.match(remoteAcceptanceRegression, /staff_team_memberships/);
  assert.match(organizationManagementMigration, /add column if not exists org_role/);
  assert.match(organizationManagementMigration, /insert into public\.organization_memberships/);
  assert.match(organizationManagementMigration, /excluded\.role = 'ADMIN'::public\.membership_role/);
  assert.match(invitationCompatibilityMigration, /create or replace function public\.create_staff_invitation\(\s*invite_email text,[\s\S]*invite_season_ids uuid\[\] default array\[\]::uuid\[\]\s*\)/);
  assert.match(invitationCompatibilityMigration, /'MEMBER'\s*\);/);
  assert.match(remoteVerifySql, /public\.create_staff_invitation\(text,text,text,text,text,text,timestamp with time zone,uuid\[\],uuid\[\]\)/);
  assert.match(remoteVerifySql, /public\.create_staff_invitation\(text,text,text,text,text,text,timestamp with time zone,uuid\[\],uuid\[\],text\)/);
  assert.match(remoteAcceptanceRegression, /org_role,\s+expires_at/s);
  assert.match(remoteAcceptanceRegression, /organization_memberships as om/);

  assert.match(createRoute, /createInviteToken/);
  assert.match(createRoute, /hashInviteToken\(token\)/);
  assert.match(createRoute, /invite_org_role/);
  assert.match(createRoute, /sendStaffInviteEmail/);
  assert.match(invitations, /requestSiteUrl/);
  assert.doesNotMatch(invitations, /NEXT_PUBLIC_APP_URL|VERCEL_PROJECT_PRODUCTION_URL/);
  assert.match(siteUrl, /NEXT_PUBLIC_SITE_URL/);
  assert.match(siteUrl, /https:\/\/clubhouse9sports\.com/);
  assert.match(acceptRoute, /accept_staff_invitation/);
  assert.match(lookupRoute, /readInvitationSummaryByHash/);
  assert.match(memberRoute, /canAdminStaffTeam/);
  assert.match(memberRoute, /hasAnotherTeamAdmin/);
  assert.match(memberRoute, /profile_team_memberships/);
  assert.match(memberRoute, /profile-staff-/);
  assert.match(memberRoute, /materializeProfileStaffMember/);
  assert.match(memberRoute, /UUID_PATTERN/);
  assert.doesNotMatch(memberRoute, /body\.email|body\.firstName|body\.lastName|body\.displayName/);
});
