import test from 'node:test';
import assert from 'node:assert/strict';
import {interpretVoice} from '../app/lib/voiceIntent.ts';
import {parseVoiceCommand} from '../app/lib/voiceCommands.ts';
import {initialBpSettings,initialBpState,buildBpPitch} from '../app/lib/liveBp.ts';
import {buildBpRunnerMove} from '../app/lib/liveBpRunnerMove.ts';
import {buildBpDefenseRep} from '../app/lib/liveBpDefenseRep.ts';
import {likelyVoiceContinuation,voiceFragmentRelation,mergeVoiceDetail,assembleVoiceFragments} from '../app/lib/voiceEventAssembler.ts';
import {HeldVoiceAudio} from '../app/lib/heldVoiceAudio.ts';
import {encodeVoiceWav,validateVoiceWav} from '../app/lib/voiceAudio.ts';
import {captureDefensePreset,defensePresetNameKey} from '../app/lib/liveBpDefensePresets.ts';
const roster=[{id:'00000000-0000-4000-8000-000000000001',aliases:['Alex Goltsch','Alex','Goltsch']},{id:'00000000-0000-4000-8000-000000000002',aliases:['Jackson Pierce','Jackson','JP']}];
const settings={...initialBpSettings(roster[1].id),source:'COACH',mode:'GAME',alignment:{RF:roster[0].id,SS:roster[1].id}};
const state={...initialBpState(),runners:[2],runnerIds:{2:roster[0].id}};
const context={domain:'live-bp',settings,state,roster,bats:'R'};
const parse=text=>interpretVoice(text,context,'test',.99);
for(const name of ['Alex','Alex Goltsch','Goltsch']) {
  test(`${name} scores as part of BIP`,()=>{const p=parse(`Single to center ${name} scores`);assert.deepEqual(p.unresolvedFields,[]);assert.equal(p.playerId,roster[1].id);assert.equal(p.draft.runnerOutcomes['2'],'score');});
  test(`${name} scored on that last play is a runner action`,()=>{const c=parseVoiceCommand(`${name} scored on that last play`,roster,settings,state);assert.deepEqual(c.problems,[]);assert.equal(c.action.kind,'runner');assert.equal(c.action.move.from,2);assert.equal(c.action.move.to,4);assert.deepEqual(buildBpRunnerMove(settings,state,c.action.move).stateAfter.runners,[]);});
}
test('same first name resolves only a unique occupied runner',()=>{const duplicate=[...roster,{id:'other',aliases:['Alex White','Alex']}];assert.deepEqual(parseVoiceCommand('Alex scores',duplicate,settings,state).problems,[]);const both={...state,runners:[1,2],runnerIds:{1:'other',2:roster[0].id}};assert.ok(interpretVoice('Single Alex scores',{...context,roster:duplicate,state:both},'test',.99).unresolvedFields.length);});
for(const phrase of ['right field made an error','right fielder made an error','right fielder booted it','right fielder clean play'])test(`${phrase} is defense only`,()=>{const c=parseVoiceCommand(phrase,roster,settings,state);assert.equal(c.action.kind,'defense');assert.deepEqual(c.problems,[]);const p=buildBpDefenseRep(settings,state,c.action.rep);assert.equal(p.hitting,undefined);assert.equal(p.pitching,undefined);assert.equal(p.defense.rep_type,null);assert.deepEqual(p.context.after,state);});
for(const occupied of [[1],[1,2],[1,2,3],[2],[3]])test(`ROE forced chain ${occupied}`,()=>{const before={...initialBpState(),runners:occupied};const p=buildBpPitch(settings,before,{outcome:'Ball in play',result:'Reached on Error',battedBall:'Ground ball'});assert.equal(new Set(p.stateAfter.runners).size,p.stateAfter.runners.length);assert.deepEqual([...p.stateAfter.runners].sort(),occupied.includes(1)?[1,...occupied.map(b=>b+1).filter(b=>b<4)]:[1,...occupied]);});
for(const phrase of ['Line drive to right','Hard ground ball to short','Fly ball center'])test(`provisional ${phrase}`,()=>assert.equal(likelyVoiceContinuation(phrase),true));
for(const phrase of ['Whiff','Ball','Foul','Called strike','JP hitting','Count one-one','Undo','Slider 78 whiff'])test(`immediate ${phrase}`,()=>assert.equal(likelyVoiceContinuation(phrase),false));
for(const [fragments,ev,result] of [[['Line drive to right','94 exit','single'],94,'Single'],[['Hard ground ball to short','88 exit','shortstop throws to first','out'],88,'Out']])test(`one rep ${fragments.join(' / ')}`,()=>{let text=fragments[0];for(const f of fragments.slice(1)){assert.equal(voiceFragmentRelation(text,f),'detail');text=mergeVoiceDetail(text,f);}const p=parse(text);assert.equal(p.draft.ev,ev);assert.equal(p.draft.result,result);assert.equal(p.draft.velocity,undefined);});
for(const next of ['Slider 78 down away whiff','JP is hitting now','Count one-one','Whiff','Ball','Foul','Line drive left'])test(`new boundary ${next}`,()=>assert.equal(voiceFragmentRelation('Line drive right',next),'boundary'));
test('explicit EV correction preserves pitch speed',()=>assert.equal(mergeVoiceDetail('84 fastball line drive 94 exit','actually 91'),'84 fastball line drive 91 exit'));
test('held whole rep keeps pitch and contact and runner dimensions',()=>{const p=interpretVoice('84 fastball low and away hard line drive to right 94 exit single runner from first goes to third',{...context,state:{...state,runners:[1],runnerIds:{1:roster[0].id}}},'held',.99);assert.deepEqual(p.unresolvedFields,[]);assert.equal(p.draft.velocity,84);assert.equal(p.draft.ev,94);assert.equal(p.draft.contactQuality,'Hard');assert.equal(p.draft.runnerOutcomes['1'],'3');});

for(const pause of [2,3,4])test(`held PCM retains ${pause}s silent pause without segmenting`,()=>{const held=new HeldVoiceAudio(48000);assert.equal(held.append(new Float32Array(48000).fill(.15)),false);assert.equal(held.append(new Float32Array(48000*pause)),false);assert.equal(held.append(new Float32Array(48000).fill(.25)),false);const samples=held.finish();assert.equal(validateVoiceWav(new Uint8Array(encodeVoiceWav(samples,48000))),pause+2);assert.equal(held.finish(),null);assert.throws(()=>held.append(new Float32Array(1)));});
test('held hard cap and cancel are explicit, one-shot boundaries',()=>{const held=new HeldVoiceAudio(16000);assert.equal(held.append(new Float32Array(16000*31)),true);assert.equal(held.seconds,30);assert.equal(held.finish(true),null);assert.equal(held.finish(),null);});
const fragment=(sequence,text,start,end,explicitEnd=false)=>({ticket:{sequence,capturedAt:start},endedAt:end,transcript:text,confidence:.97,status:'waiting',explicitEnd});
async function assemble(first,fragments,options={}){let now=first.endedAt;let ticks=0;return assembleVoiceFragments(first,{next:seq=>fragments.find(f=>f.ticket.sequence===seq && f.ticket.capturedAt<=now),speaking:()=>null,interrupted:()=>false,active:()=>true,wait:async()=>{now+=25;if(++ticks>1000)throw new Error('Unbounded assembler');},now:()=>now,provisional:()=>{},...options});}
test('three naturally paused segments assemble once and preserve first ticket',async()=>{const first=fragment(1,'Line drive right',0,1000),ev=fragment(2,'94 exit',2500,3000),result=fragment(3,'single',4500,5000);const batch=await assemble(first,[ev,result]);assert.equal(batch.text,'Line drive right, 94 exit, single');assert.equal(batch.merged.length,2);assert.ok(ev.absorbed&&result.absorbed);assert.equal(first.ticket.sequence,1);});
test('long silence flushes partial data, never loses next pitch',async()=>{const next=fragment(2,'Slider 78 whiff',5000,6000);const batch=await assemble(fragment(1,'Line drive right',0,1000),[next]);assert.equal(batch.merged.length,0);assert.equal(next.absorbed,undefined);});
test('hitter change flushes old rep before changing hitter',async()=>{const next=fragment(2,'JP hitting',1500,2000);const batch=await assemble(fragment(1,'Line drive right',0,1000),[next]);assert.equal(batch.text,'Line drive right');assert.equal(batch.merged.length,0);});
test('manual sequence gap forbids enrichment',async()=>{const next=fragment(3,'94 exit',1500,2000);const batch=await assemble(fragment(1,'Line drive right',0,1000),[next],{interrupted:()=>true});assert.equal(batch.merged.length,0);});
test('hold release never waits for continuation',async()=>{const batch=await assemble(fragment(1,'Line drive right',0,1000,true),[],{wait:async()=>{throw new Error('Held rep waited');}});assert.equal(batch.merged.length,0);});
test('short pitch burst never enters continuation wait',async()=>{for(const text of ['Whiff','Ball','Foul','Called strike']){const batch=await assemble(fragment(1,text,0,1000),[],{wait:async()=>{throw new Error('Complete command delayed');}});assert.equal(batch.text,text);}});
test('provider reordering waits for adjacent transcription',async()=>{const next=fragment(2,undefined,1200,2000);let time=1300;const batch=await assemble(fragment(1,'Line drive right',0,1000),[next],{now:()=>time,next:sequence=>sequence===2?next:undefined,speaking:()=>null,wait:async()=>{time+=100;if(time===1800)next.transcript='94 exit';if(time>8000)throw new Error('hung');}});assert.equal(batch.merged.length,1);});
for(const phrase of ['Team one is on defense','Team 1 is on defense','Team1 on defense','Switch to team one','Back to Team 1','Load team one'])test(`preset ${phrase}`,()=>{const s={...settings,defensePresets:[captureDefensePreset(settings,'preset','Team1')]};const c=parseVoiceCommand(phrase,roster,s,state);assert.deepEqual(c.problems,[]);assert.deepEqual(c.patch.alignment,s.alignment);});
test('normalized duplicate preset names require review',()=>{const s={...settings,defensePresets:[captureDefensePreset(settings,'a','Team1'),captureDefensePreset(settings,'b','Team 1')]};assert.ok(parseVoiceCommand('Team one is on defense',roster,s,state).problems.length);assert.equal(defensePresetNameKey('Team two'),'team2');});
for(const phrase of ['94 exit on that last play','94 exit on the last one','that was 94 exit'])test(`bounded explicit enrichment ${phrase}`,()=>assert.deepEqual(parseVoiceCommand(phrase,roster,settings,state).action,{kind:'amend',ev:94}));
test('explicit last-play defense is distinct from new standalone rep',()=>assert.equal(parseVoiceCommand('right fielder made the error on that',roster,settings,state).action.rep.lastPlay,true));
test('optional BIP details may remain unknown without inventing batter or runner advancement',()=>{const p=parse('Line drive right');assert.deepEqual(p.unresolvedFields,[]);const built=buildBpPitch(settings,state,p.draft);assert.equal(built.context.result,'Ball in play');assert.deepEqual(built.stateAfter.runners,state.runners);assert.deepEqual(built.stateAfter.runnerIds,state.runnerIds);assert.equal(built.hitting.exit_velocity_mph,undefined);});
