-- CLU9-3: curated, versioned Baseball Knowledge Bank.
-- V1 intentionally uses Postgres metadata filters plus full-text search. The
-- current beta corpus is small enough that embeddings would add cost and an
-- operational re-embedding job before they add meaningful retrieval value.

create table if not exists public.baseball_knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  category text not null,
  subcategory text,
  level text,
  governing_body text,
  version text,
  source_name text,
  source_reference text,
  status text not null default 'draft'
    check (status in ('draft', 'candidate', 'reviewed', 'verified', 'stale', 'expired', 'rejected')),
  verified_at timestamptz,
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists baseball_knowledge_documents_filter_idx
  on public.baseball_knowledge_documents(category, level, governing_body, version, status);

create index if not exists baseball_knowledge_documents_active_idx
  on public.baseball_knowledge_documents(status, expires_at)
  where status in ('reviewed', 'verified');

create table if not exists public.baseball_knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.baseball_knowledge_documents(id) on delete cascade,
  ordinal smallint not null default 1 check (ordinal > 0),
  content text not null check (char_length(trim(content)) > 0),
  search_vector tsvector generated always as (to_tsvector('english', content)) stored,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (document_id, ordinal)
);

create index if not exists baseball_knowledge_chunks_search_idx
  on public.baseball_knowledge_chunks using gin(search_vector);

create index if not exists baseball_knowledge_chunks_document_idx
  on public.baseball_knowledge_chunks(document_id, ordinal);

alter table public.baseball_knowledge_documents enable row level security;
alter table public.baseball_knowledge_chunks enable row level security;

drop policy if exists "Authenticated users can read trusted baseball knowledge documents" on public.baseball_knowledge_documents;
create policy "Authenticated users can read trusted baseball knowledge documents"
  on public.baseball_knowledge_documents
  for select
  to authenticated
  using (
    status in ('reviewed', 'verified')
    and (expires_at is null or expires_at > now())
  );

drop policy if exists "Authenticated users can read trusted baseball knowledge chunks" on public.baseball_knowledge_chunks;
create policy "Authenticated users can read trusted baseball knowledge chunks"
  on public.baseball_knowledge_chunks
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.baseball_knowledge_documents d
      where d.id = baseball_knowledge_chunks.document_id
        and d.status in ('reviewed', 'verified')
        and (d.expires_at is null or d.expires_at > now())
    )
  );

-- Writes are intentionally reserved for the server-side admin repository. The
-- service role can manage drafts/reviewed items without exposing an editor to
-- normal clients, while authenticated users only receive trusted content.
grant select on public.baseball_knowledge_documents to authenticated;
grant select on public.baseball_knowledge_chunks to authenticated;

comment on table public.baseball_knowledge_documents is
  'Versioned metadata for curated baseball knowledge. Store concise summaries and source references, not copied rulebooks.';
comment on table public.baseball_knowledge_chunks is
  'Bounded searchable knowledge content. V1 uses indexed Postgres full-text retrieval; embeddings may be added later if corpus size or miss-rate justifies them.';

create temporary table _baseball_knowledge_seed (
  slug text not null,
  title text not null,
  category text not null,
  subcategory text,
  level text,
  governing_body text,
  version text,
  source_name text,
  source_reference text,
  status text not null,
  verified_at timestamptz,
  content text not null
) on commit drop;

insert into _baseball_knowledge_seed
  (slug, title, category, subcategory, level, governing_body, version, source_name, source_reference, status, verified_at, content)
values
  ('statistics-avg', 'Batting Average', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Batting average (AVG) is hits divided by at-bats. It describes how often a batter records a hit in an at-bat, but it does not include walks and should be read with on-base and contact-quality measures.$$),
  ('statistics-obp', 'On-Base Percentage', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$On-base percentage (OBP) measures how often a batter reaches base through a hit, walk, or hit by pitch, using the applicable official denominator. It gives more context than batting average because walks count.$$),
  ('statistics-slg', 'Slugging Percentage', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Slugging percentage (SLG) is total bases divided by at-bats. Singles count as one base, doubles two, triples three, and home runs four, so SLG reflects extra-base impact as well as hits.$$),
  ('statistics-ops', 'OPS', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$OPS is on-base percentage plus slugging percentage. It is a quick offensive snapshot, not a complete player evaluation; sample size, competition, contact quality, and swing decisions still matter.$$),
  ('statistics-era', 'Earned Run Average', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Earned run average (ERA) estimates earned runs allowed per nine innings. It depends on official scoring and innings recorded, so it should be interpreted with workload and defensive context.$$),
  ('statistics-whip', 'WHIP', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$WHIP is walks plus hits allowed divided by innings pitched. It describes how many non-homer runners a pitcher allows per inning, but it does not directly include hit batters or defensive errors.$$),
  ('statistics-k-percent', 'Strikeout Rate', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Strikeout rate (K%) is strikeouts divided by the selected denominator, commonly batters faced for pitchers or plate appearances for hitters. Always name the denominator when comparing sources.$$),
  ('statistics-bb-percent', 'Walk Rate', 'Statistics', 'Hitting/Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Walk rate (BB%) is walks divided by the selected opportunities, commonly plate appearances for hitters or batters faced for pitchers. A rate is more useful when the denominator and sample are clear.$$),
  ('statistics-babip', 'BABIP', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$BABIP is batting average on balls in play. It excludes strikeouts and home runs and can move quickly in small samples, so it is a context metric rather than a standalone verdict.$$),
  ('statistics-contact-percent', 'Contact Percentage', 'Statistics', 'Clubhouse metric', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Clubhouse tracking definition; confirm team configuration.', 'reviewed', '2026-09-01T00:00:00Z', $$Clubhouse Contact % is a development metric based on the contact outcomes recorded in Clubhouse hitting events. It is not automatically the same as a league or MLB contact-rate formula; use the tracked-event denominator shown with the result.$$),
  ('statistics-hard-contact-percent', 'Hard Contact Percentage', 'Statistics', 'Clubhouse metric', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Clubhouse tracking definition; confirm team configuration.', 'reviewed', '2026-09-01T00:00:00Z', $$Clubhouse Hard Contact % is the share of tracked contact events labeled Hard under the team tracking setup. It describes recorded contact quality and should be paired with the number of tracked balls in play.$$),
  ('statistics-exit-velocity', 'Exit Velocity', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Exit velocity is the speed of the ball off the bat, usually measured in miles per hour. Averages and peaks answer different questions, and small samples can make both unstable.$$),
  ('statistics-strike-percent', 'Strike Percentage', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Strike % is strikes divided by total tracked pitches under the selected definition. Called strikes, swings, and balls in play may be handled differently by a system, so inspect the denominator before comparing pitchers.$$),
  ('statistics-csw-percent', 'CSW Percentage', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$CSW% is called strikes plus whiffs divided by total tracked pitches. It measures a pitcher's ability to earn called strikes or misses without relying only on balls put in play.$$),
  ('statistics-fielding-percent', 'Fielding Percentage', 'Statistics', 'Defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Fielding percentage is putouts plus assists divided by putouts, assists, and errors. It is a narrow official statistic and does not capture range, positioning, difficulty, or every defensive contribution.$$),
  ('statistics-first-pitch-strike', 'First-Pitch Strike', 'Statistics', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$First-pitch strike rate is the share of plate appearances or tracked at-bats that begin with a strike under the selected definition. It can describe early-count control, but the denominator must be stated.$$),
  ('statistics-chase-rate', 'Chase Rate', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Chase rate is the share of swings at pitches outside the defined strike zone. The zone definition and whether takes are included matter, so compare only like-for-like tracking samples.$$),
  ('statistics-zone-contact', 'Zone Contact', 'Statistics', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$Zone contact rate is contact made on swings at pitches in the defined strike zone. It helps separate recognition and bat-to-ball skill from overall contact, but it depends on reliable pitch-location and contact tracking.$$),
  ('terminology-plate-appearance', 'Plate Appearance', 'Terminology', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$A plate appearance is a completed turn at bat that counts toward a batter's official plate-appearance total. It can end in many ways, including a hit, walk, strikeout, out, or sacrifice.$$),
  ('terminology-at-bat', 'At-Bat', 'Terminology', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$An at-bat is an official batting opportunity used in the denominator for batting average. Walks, hit by pitch, sacrifices, and some other outcomes are plate appearances but not at-bats.$$),
  ('terminology-count', 'The Count', 'Terminology', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$The count is the current number of balls and strikes in a plate appearance. Count leverage changes what a hitter and pitcher can reasonably expect and influences approach and pitch selection.$$),
  ('terminology-fair-foul', 'Fair Ball and Foul Ball', 'Terminology', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$A fair ball first touches fair territory or is otherwise judged fair under the applicable rules. A foul ball touches foul territory or is judged foul, with special rules for foul tips and balls that are caught.$$),
  ('terminology-hard-hit', 'Hard-Hit Ball', 'Terminology', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$A hard-hit ball is a ball struck with high exit velocity under the tracking system's threshold. The threshold can vary by data provider, so the source definition should travel with the number.$$),
  ('terminology-extra-base-hit', 'Extra-Base Hit', 'Terminology', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; standard baseball definition.', 'reviewed', '2026-09-01T00:00:00Z', $$An extra-base hit is a hit that allows the batter to reach at least second base without an error, including a double, triple, or home run.$$),
  ('rules-balk', 'Balk', 'Rules', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A balk is an illegal action by a pitcher with runners on base that may deceive or unfairly disadvantage the offense. The penalty and exact list of illegal actions depend on the governing code, so coaches should use the applicable rulebook for an official ruling.$$),
  ('rules-nfhs-2026-balk', 'NFHS 2026 Balk Basics', 'Rules', 'Pitching', 'High School', 'NFHS', '2026', 'NFHS Baseball Rules', '2026 edition, Rule 6-2-5; concise summary, not a reproduced rulebook.', 'verified', '2026-09-01T00:00:00Z', $$For NFHS 2026 context, a balk is an illegal act by the pitcher with a runner or runners on base that may be intended to deceive. The precise penalty and required legal pitching actions come from the NFHS code; this entry is a concise reference and not a replacement for the rulebook.$$),
  ('rules-infield-fly', 'Infield Fly', 'Rules', 'Defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$The infield-fly rule can protect the offense when there are runners in force-play situations and a fair fly ball can be caught by an infielder with ordinary effort. The umpire's judgment, outs, runners, and governing code all matter.$$),
  ('rules-dropped-third-strike', 'Dropped Third Strike', 'Rules', 'Catching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$On a dropped or uncaught third strike, the batter may be able to run to first under the applicable code and force conditions. The defense must know when the batter is entitled to run and how to complete the out.$$),
  ('rules-tag-up', 'Tag-Up', 'Rules', 'Baserunning', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A runner on base generally must retouch the occupied base after a caught fly ball before advancing. The runner may leave after the catch, and the defense can appeal a failure to retouch under the applicable rules.$$),
  ('rules-force-play', 'Force Play', 'Rules', 'Baserunning', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A force play exists when a runner is required to advance because the batter became a runner or another runner is forced behind them. A force out can be recorded by tagging the forced base before the runner arrives.$$),
  ('rules-appeal', 'Appeal Play', 'Rules', 'Baserunning', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$An appeal asks an umpire to rule on a runner's or batter-runner's failure to meet a specific requirement, such as missing a base or failing to tag up. Timing and dead-ball procedures vary by code.$$),
  ('rules-interference', 'Interference', 'Rules', 'Offense/Defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$Interference is an act that obstructs, impedes, or confuses a fielder or otherwise violates a protected play. The responsible person and the play situation determine the penalty; it is different from obstruction.$$),
  ('rules-obstruction', 'Obstruction', 'Rules', 'Defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$Obstruction occurs when a fielder who is not legally fielding the ball impedes a runner. The umpire applies the penalty or awards bases according to the play and governing code.$$),
  ('rules-designated-hitter', 'Designated Hitter Basics', 'Rules', 'Lineup', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A designated hitter bats in the lineup without serving as the defensive player for that batting slot under the applicable rules. DH options, substitutions, and whether the pitcher can return to the lineup depend on the governing code.$$),
  ('rules-substitutions', 'Substitution Basics', 'Rules', 'Lineup', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A substitution replaces a player in the lineup or defensive alignment. The substitute's batting order position and re-entry rights are controlled by the governing code, so a coach should confirm the competition rules before making a strategic change.$$),
  ('rules-set-position', 'Set Position Basics', 'Rules', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$With runners on base, the pitcher must use a legal preliminary position and complete the required motion without an illegal interruption. The legal set-position details and penalties vary by governing code.$$),
  ('rules-pitching-delivery', 'Pitching Delivery Basics', 'Rules', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$A legal pitching delivery includes the required contact with the rubber, preliminary position, motion, and release. Coaches should separate mechanical coaching from an umpire's code-specific judgment about a legal pitch.$$),
  ('rules-illegal-pitch', 'Illegal Pitch', 'Rules', 'Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$An illegal pitch is a delivery that violates the applicable pitching rules. The result can differ with runners on base, a batter in the box, or a dead-ball situation, so do not generalize a penalty across rule codes.$$),
  ('rules-catcher-interference', 'Catcher Interference', 'Rules', 'Catching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Concise coaching summary; governing-body specifics may vary.', 'reviewed', '2026-09-01T00:00:00Z', $$Catcher interference occurs when the catcher or their equipment hinders the batter's opportunity to hit the pitch. The umpire applies the appropriate award or penalty under the governing code.$$),
  ('hitting-pull-side', 'Pull Side', 'Hitting', 'Contact direction', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pull-side contact is hit toward the side of the field associated with the batter's natural pull direction. It can be useful when timing and pitch location support it, but pulling every pitch is not a universal goal.$$),
  ('hitting-opposite-field', 'Opposite Field', 'Hitting', 'Contact direction', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Opposite-field contact travels toward the side of the field away from the batter's natural pull side. It often reflects letting the ball travel, but the best approach depends on pitch location, timing, and intent.$$),
  ('hitting-middle', 'Middle of the Field', 'Hitting', 'Contact direction', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Middle-field contact travels through the central part of the field. Using the middle as an approach cue can help a hitter stay connected to pitch direction without turning it into a rigid swing rule.$$),
  ('hitting-contact-types', 'Launch and Contact Types', 'Hitting', 'Batted-ball results', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Line drives, ground balls, fly balls, and pop-ups describe different batted-ball results. They are useful for describing what happened, but no single contact type is automatically good or bad without location, exit velocity, and game context.$$),
  ('hitting-chase', 'Chase', 'Hitting', 'Plate discipline', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Chase means swinging at a pitch outside the defined strike zone. A low chase rate can support better counts, but a hitter still needs an effective plan for attacking hittable pitches.$$),
  ('hitting-zone-contact', 'Zone Contact Approach', 'Hitting', 'Plate discipline', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Zone contact is contact made on swings at strikes. Improving it usually involves recognizing the pitch and location early enough to match the swing, rather than simply swinging harder.$$),
  ('hitting-pitch-recognition', 'Pitch Recognition', 'Hitting', 'Approach', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch recognition is identifying pitch type, speed, and location early enough to make a useful swing decision. It is best evaluated with both decision outcomes and the quality of contact that follows.$$),
  ('hitting-two-strike-approach', 'Two-Strike Approach', 'Hitting', 'Approach', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A two-strike approach is a hitter's plan for protecting the zone, competing against tougher pitches, and avoiding a passive or panicked at-bat. The plan should remain specific to the hitter and situation.$$),
  ('hitting-velocity-adjustment', 'Velocity Adjustment', 'Hitting', 'Timing', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Velocity adjustment is changing timing and decision-making to handle a faster or slower pitch. A hitter may need an earlier move, a shorter decision window, or a clearer zone plan; it is not only a mechanical change.$$),
  ('hitting-breaking-ball-recognition', 'Breaking-Ball Recognition', 'Hitting', 'Pitch recognition', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Breaking-ball recognition is distinguishing a breaking pitch's shape and location early enough to decide whether to swing. Tracking data can show outcomes, but it cannot by itself identify every recognition error.$$),
  ('hitting-timing', 'Hitting Timing', 'Hitting', 'Timing', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Timing is coordinating the hitter's move and contact point with the pitch's arrival. Late, early, and on-time contact should be considered with pitch speed, location, and contact quality.$$),
  ('hitting-plate-discipline', 'Plate Discipline', 'Hitting', 'Approach', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Plate discipline is the ability to make repeatable swing decisions that prioritize hittable pitches and manage the count. It includes selectivity and readiness to attack, not simply taking more pitches.$$),
  ('hitting-barrel', 'Barrel', 'Hitting', 'Contact quality', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A barrel is a batted-ball combination of exit velocity and launch angle associated with especially strong contact under a provider's definition. The exact threshold is source-specific and should accompany the statistic.$$),
  ('hitting-approach-by-location', 'Approach by Pitch Location', 'Hitting', 'Approach', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A hitter's approach should account for where the pitch enters the zone. The goal is not to force one swing path everywhere, but to preserve balance, timing, and a plan for the pitch the hitter can handle best.$$),
  ('pitching-command-control', 'Command vs Control', 'Pitching', 'Pitching fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Control is the ability to throw strikes. Command is the ability to locate a pitch intentionally within or around the zone. A pitcher can show control without consistently commanding the desired target.$$),
  ('pitching-pitch-types', 'Pitch Types', 'Pitching', 'Pitch design', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Common pitch types include fastballs, sliders, curveballs, changeups, sinkers, cutters, and splitters. A pitch name should describe the intended movement or grip family only when the tracking context supports that label.$$),
  ('pitching-glove-side', 'Glove Side', 'Pitching', 'Location', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Glove side is the side of the plate or target area toward the pitcher's glove hand. Coaches often use it as a location cue, but the result also depends on handedness, pitch type, and the batter's position.$$),
  ('pitching-arm-side', 'Arm Side', 'Pitching', 'Location', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Arm side is the side of the plate or target area toward the pitcher's throwing arm. It is a relative location term, not a guarantee that every pitch will move there.$$),
  ('pitching-strike-percent', 'Pitch Strike Plan', 'Pitching', 'Pitch execution', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Strike percentage can show whether a pitcher is filling the zone, but it does not distinguish a well-located strike from a hittable one. Pair it with count, contact, and location context.$$),
  ('pitching-first-pitch-strike', 'First-Pitch Strike Plan', 'Pitching', 'Pitch execution', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A first-pitch strike can put a pitcher ahead in the count, but the best first pitch still needs to be competitive and located. Track the outcome rather than treating any strike as equally valuable.$$),
  ('pitching-whiff', 'Whiff', 'Pitching', 'Pitch execution', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A whiff is a swing that does not make contact. Whiff rate depends on the swing denominator and can be useful for pitch effectiveness when paired with chase, zone, and count context.$$),
  ('pitching-csw', 'CSW Pitching Context', 'Pitching', 'Pitch execution', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$CSW combines called strikes and whiffs. It can reveal pitches that win without contact, but it should be read with pitch count, location quality, and sample size.$$),
  ('pitching-velocity', 'Pitch Velocity', 'Pitching', 'Pitch execution', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch velocity is the speed of a pitch as measured by the tracking system. Average and maximum velocity answer different questions, and a faster pitch is not automatically a better pitch without command and movement.$$),
  ('pitching-sequencing', 'Pitch Sequencing', 'Pitching', 'Strategy', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch sequencing is choosing and ordering pitches so that location, speed, and movement challenge the hitter's expectations. A sequence should be evaluated with count, hitter tendencies, and execution rather than pitch names alone.$$),
  ('pitching-count-leverage', 'Count Leverage', 'Pitching', 'Strategy', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Count leverage describes how balls and strikes change the likely advantage for a hitter or pitcher. It influences risk tolerance, zone strategy, and which pitches can be used effectively.$$),
  ('pitching-location', 'Pitch Location', 'Pitching', 'Location', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch location is where the pitch crosses the plate or reaches a tracked target. Location analysis is meaningful only when the coordinate system, zone, handedness, and sample quality are understood.$$),
  ('pitching-pitch-shape', 'Pitch Shape', 'Pitching', 'Pitch design', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch shape describes movement and velocity characteristics that distinguish one pitch from another. Shape should support a pitcher's intent and command; it is not a standalone grade.$$),
  ('pitching-tunneling', 'Pitch Tunneling', 'Pitching', 'Pitch design', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Pitch tunneling describes pitches that look similar early in flight before separating late. It can make recognition harder, but reliable tracking and game context are needed before making a strong claim.$$),
  ('defense-routine-play', 'Routine Defensive Play', 'Defense', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A routine play is a defensive opportunity expected to be handled with ordinary effort for that position and situation. The difficulty label should be defined by the coaching or tracking system, not inferred from the outcome alone.$$),
  ('defense-forehand-backhand', 'Forehand and Backhand', 'Defense', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Forehand and backhand describe the side of the glove path used to field a ball. Good footwork, body position, transfer, and throw decision matter as much as which side the ball is fielded on.$$),
  ('defense-cutoff', 'Cutoff Responsibilities', 'Defense', 'Team defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A cutoff player receives a throw in the relay path and helps redirect it to the correct base. The responsibility depends on ball location, runners, outs, and the team's communication plan.$$),
  ('defense-relay', 'Relay Play', 'Defense', 'Team defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A relay play uses a fielder between the outfield and an infield target to move the ball efficiently. Alignment, footwork, glove exchange, and a clear target reduce extra bases.$$),
  ('defense-force-tag', 'Force and Tag Defense', 'Defense', 'Team defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Defenders should know whether a runner can be retired by touching a base for a force out or by tagging the runner. The correct choice depends on the force status, ball control, and play timing.$$),
  ('defense-double-play', 'Double-Play Fundamentals', 'Defense', 'Team defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A double play retires two offensive players in one continuous play. Footwork, feed quality, target choice, communication, and the force status all influence whether the opportunity is completed.$$),
  ('defense-position-responsibilities', 'Position Responsibilities', 'Defense', 'Team defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Position responsibilities describe where a defender should align and what bases, backups, or cutoffs they own in a situation. Responsibilities should be taught as a connected team plan, not isolated movement patterns.$$),
  ('defense-throw-accuracy', 'Throw Accuracy', 'Defense', 'Throwing', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Throw accuracy is the share or count of throws that reach the intended target under the tracking definition. It should be paired with throw difficulty, decision quality, and whether the throw was necessary.$$),
  ('defense-fielding-fundamentals', 'Fielding Fundamentals', 'Defense', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Fielding fundamentals include readiness, first step, route, body control, secure catch, transfer, and an accurate decision-driven throw. A single result does not diagnose which part of the sequence needs work.$$),
  ('catching-receiving', 'Catcher Receiving', 'Catching', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Receiving is presenting and securing a pitch with quiet, controlled glove work while maintaining a position that supports the next play. Evaluation should respect pitch location and movement rather than judging every miss equally.$$),
  ('catching-blocking', 'Catcher Blocking', 'Catching', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Blocking is using body position, glove, and recovery skills to keep a pitch in front. The best choice depends on pitch location, runner situation, and the catcher's ability to recover and make the next play.$$),
  ('catching-transfer', 'Catcher Transfer', 'Catching', 'Throwing', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A catcher transfer is the movement from receiving the ball to a throwing grip and release. A clean transfer can reduce exchange time, but it must remain secure and appropriate to the pitch and game situation.$$),
  ('catching-communication', 'Catcher Communication', 'Catching', 'Leadership', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Catchers help organize the defense through clear signs, pitch communication, coverage calls, and situational reminders. The exact communication plan belongs to the coaching staff and should be consistent with the team's system.$$),
  ('baserunning-lead', 'Baserunner Lead', 'Baserunning', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A baserunner lead is the distance and body position taken from a base before the pitch or play. It should balance gaining ground with the ability to return safely and react to the pitcher.$$),
  ('baserunning-first-step', 'Baserunning First Step', 'Baserunning', 'Fundamentals', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$The first step is the runner's initial movement after reading the ball, pitcher, or coach. A good first step comes from recognizing the situation quickly rather than simply moving early.$$),
  ('baserunning-read-react', 'Read and React', 'Baserunning', 'Decision-making', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Read-and-react baserunning means identifying the ball flight, fielder control, outs, and base situation before committing to the next base. Aggressive running is useful only when it is informed by the play.$$),
  ('baserunning-extra-base', 'Taking the Extra Base', 'Baserunning', 'Decision-making', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Taking an extra base depends on ball location, outfielder control, relay path, runner speed, and game context. A clear go-or-stop decision and efficient turn often matter more than raw speed.$$),
  ('strategy-bunt', 'Bunting Strategy', 'Strategy', 'Offense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Bunting strategy depends on the score, inning, outs, runners, hitter skill, defense, and competition rules. It should be a purposeful tactical choice, not a default response to pressure.$$),
  ('strategy-count-leverage', 'Count Strategy', 'Strategy', 'Offense/Pitching', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Count strategy is adjusting swing decisions and pitch choices as the ball-strike count changes. The best plan protects the team's goals while accounting for the hitter, pitcher, outs, and base situation.$$),
  ('strategy-situational-defense', 'Situational Defense', 'Strategy', 'Defense', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Situational defense organizes positioning, coverage, backups, and throw priorities around the score, outs, runners, and likely batted-ball outcomes. The team plan should be explicit before the pitch.$$),
  ('strategy-practice-transfer', 'Practice to Game Transfer', 'Strategy', 'Development', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Practice-to-game transfer asks whether a skill appears under game pressure, not whether every practice result predicts a game outcome. Compare like metrics and acknowledge differences in volume, intent, and competition.$$),
  ('development-deliberate-practice', 'Deliberate Practice', 'Development', 'Learning', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Deliberate practice has a clear purpose, a manageable challenge, feedback, and a way to observe progress. More repetitions are not automatically better if the task or feedback is unclear.$$),
  ('development-sample-size', 'Sample Size', 'Development', 'Measurement', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$Sample size is the number of tracked opportunities behind a metric. Larger samples usually make a rate more stable, but the right sample depends on the skill, event quality, and decision the coach is trying to make.$$),
  ('development-trend', 'Trend vs Snapshot', 'Development', 'Measurement', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary.', 'reviewed', '2026-09-01T00:00:00Z', $$A snapshot describes one period; a trend compares multiple periods using consistent definitions. A trend should show the time window and denominator so that changes in tracking volume are not mistaken for skill change.$$),
  ('development-age-benchmark', 'Age and Level Benchmarks', 'Development', 'Measurement', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 summary; no universal age benchmark.', 'reviewed', '2026-09-01T00:00:00Z', $$Age and level benchmarks are context, not a diagnosis or a guarantee. A responsible comparison needs a verified population, matching measurement method, and appropriate competition level; do not invent a benchmark from a single player result.$$),
  ('strength-training-load', 'Training Load', 'Strength', 'Training', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary; not medical advice.', 'reviewed', '2026-09-01T00:00:00Z', $$Training load is the amount and intensity of work completed over a period. Coaches should monitor it with the athlete's plan and qualified staff, avoiding conclusions about injury or medical status from workload data alone.$$),
  ('strength-recovery', 'Recovery Basics', 'Strength', 'Training', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Curated V1 coaching summary; not medical advice.', 'reviewed', '2026-09-01T00:00:00Z', $$Recovery supports the ability to train and compete consistently through sleep, nutrition, hydration, rest, and appropriate workload planning. Individual medical or pain concerns should go to qualified professionals rather than an analytics assistant.$$),
  ('practice-reps', 'Practice Repetitions', 'Practice', 'Measurement', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Clubhouse tracking definition; confirm team configuration.', 'reviewed', '2026-09-01T00:00:00Z', $$Practice reps are the tracked opportunities recorded in a practice context. The number describes volume, not performance quality, and should be read with the drill, intent, and event type.$$),
  ('practice-contact-quality', 'Practice Contact Quality', 'Practice', 'Hitting', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Clubhouse tracking definition; confirm team configuration.', 'reviewed', '2026-09-01T00:00:00Z', $$Practice contact quality summarizes how recorded contact was labeled under the Clubhouse tracking setup. It is useful for comparing like sessions, but does not automatically predict game production.$$),
  ('practice-data-coverage', 'Practice Data Coverage', 'Practice', 'Measurement', 'General', null, null, 'Clubhouse Baseball Knowledge Bank', 'Clubhouse tracking definition; confirm team configuration.', 'reviewed', '2026-09-01T00:00:00Z', $$Practice data coverage describes how many sessions, players, and event fields are actually tracked. A coverage note is part of the answer because an untracked event cannot be treated as a poor result.$$);

insert into public.baseball_knowledge_documents
  (slug, title, category, subcategory, level, governing_body, version, source_name, source_reference, status, verified_at)
select slug, title, category, subcategory, level, governing_body, version, source_name, source_reference, status, verified_at
from _baseball_knowledge_seed
on conflict (slug) do nothing;

insert into public.baseball_knowledge_chunks (document_id, ordinal, content, metadata)
select d.id, 1, seed.content, jsonb_build_object('seed', 'CLU9-3', 'source_name', seed.source_name)
from _baseball_knowledge_seed seed
join public.baseball_knowledge_documents d on d.slug = seed.slug
where not exists (
  select 1
  from public.baseball_knowledge_chunks c
  where c.document_id = d.id
    and c.ordinal = 1
);
